### ISSUE TITLE
PAP accuracy much higher than what is described in the paper.

### ISSUE THREAD

**Issue by parasdahiya** [garroud/self-rectification#1]
Do you have any idea why your implementation gives a PAP accuracy of 97% for a threshold of 1 which the paper says that the algorithm gives is 80-83% (for the same threshold)?

**Comment by garroud** [comment]
That is possible. The value presented in the paper is the average of 1000 images, and 0.97 is only a value from a sample.

**Comment by parasdahiya** [comment]
Okay.
